### ISSUE TITLE
⭐ add to Awesome NestJS repo

### ISSUE THREAD

**Issue by micalevisk** [msanvarov/nest-rest-mongo-boilerplate#1025]
please add all of your nestjs boilerplates repositories to https://github.com/nestjs/awesome-nestjs#boilerplate :)

**Comment by micalevisk** [comment]
ping @msanvarov

**Comment by msanvarov** [comment]
Hey sorry for the late replies on this. I'm doing an Nx migration on this repo. Once completed, more than happy to do that 😊
