### ISSUE TITLE
dependency issue with fastify

### ISSUE THREAD

**Issue by tmushayahama** [msanvarov/nest-rest-mongo-boilerplate#459]
@nestjs/platform-fastify expects fastify version 2.15
fastify-helmet needs fastify > 3

etc

**Comment by msanvarov** [comment]
Thanks for letting me. I will resolve this issue. Sorry for the late reply 😢

**Comment by msanvarov** [comment]
Fixed with https://github.com/msanvarov/nest-rest-mongo-boilerplate/commit/e9a1e82963085a4ee3baa8304789bd9891a04a01
